# Auto-generated by release workflow. Do not edit manually.
class Jl < Formula
  desc "A JSON log pretty-printer"
  homepage "https://github.com/genuss/jl"
  license "MIT"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/genuss/jl/releases/download/v0.1.0/jl-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/genuss/jl/releases/download/v0.1.0/jl-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/genuss/jl/releases/download/v0.1.0/jl-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/genuss/jl/releases/download/v0.1.0/jl-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "jl"
    generate_completions_from_executable(bin/"jl", "--completions")
  end

  test do
    pipe_output("#{bin}/jl", '{"message":"hello"}', 0)
  end
end
